### ISSUE TITLE
Supporting GDELT V2

### ISSUE THREAD

**Issue by TerenceLiu98** [shaptonstahl/GDELTtools#4]
Is there any plan of supporting the [GDELT Version 2](https://blog.gdeltproject.org/gdelt-2-0-our-global-world-in-realtime/)?

**Comment by shaptonstahl** [comment]
I've started working on fixing the package for GDELT v1. I do plan to address v2 after that.

**Comment by TerenceLiu98** [comment]
@shaptonstahl Thanks for the response! Looking forward to the v2 script :)
